### PR TITLE
[Fix] set language callback

### PR DESCRIPTION
**Pull request by tanaynigam**
# Description
## One Line Summary
Add device info handler success and failure callbacks to `internalSync`.

### Motivation
Adds device info handler success callback used as the `setLanguage` callback in the `internalSync` method and a device info handler failure callback in `doPutSync` method of `UserStateSynchronizer`

### Scope
* Add `deviceInfoHandlersPerformOnSuccess` in `internalSync` method of `UserStateSynchronizer`
* Add `deviceInfoHandlersPerformOnFailure` in `doPutSync` method of `UserStateSynchronizer`
* Use runnable to implement `OneSignalStateSynchronizer.updateDeviceInfo` in the `setLanguage` implementation of OneSignal Android

# Testing
## Unit testing
* Unit test for callbacks running successfully

## Manual testing
* Tested on Android device to successfully execute all intended callback

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [ ] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [ ] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1593)

### CODE REVIEW

**Review by nan-li — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1593)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jkasten2 and @tanaynigam)

___
*[`OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java` line 1797 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1593#-N2XqZlp0o43m-R-OZ_j:-N2XqZlp0o43m-R-OZ_k:b-4moz10) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/6340b2ce246303434915727c178ed21876cd4f21/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L1797)):*
> ```Java
>       };
> 
>       // If pendingTaskExecutor is running, there might be sendTags tasks running, use it to run sendTagsRunnable to keep order call
> ```

Unsure of what this comment means, can you clarify why the `OneSignalStateSynchronizer.updateDeviceInfo` call is being made a runnable and checked with `shouldRunTaskThroughQueue()`? 

Why is this change made, or what the before/after is?

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1593)* status: all files reviewed, 2 unresolved discussions (waiting on @tanaynigam)

___
*[`OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java` line 1798 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1593#-N2YRb_DDYh1TqoiR2s2:-N2YRb_DDYh1TqoiR2s3:b-7awd6q) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/6340b2ce246303434915727c178ed21876cd4f21/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L1798)):*
> ```Java
> 
>       // If pendingTaskExecutor is running, there might be sendTags tasks running, use it to run sendTagsRunnable to keep order call
>       if (taskRemoteController.shouldRunTaskThroughQueue()) {
> ```

This should use `taskRemoteController.shouldQueueTaskForInit` for consistently with the other public methods, unless there is a specific reason this is used instead.



_Code quote:_
```Java
shouldRunTaskThroughQueue()
```

**Review by nan-li — APPROVED** [review]
LGTM

**Review by jkasten2 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1593#-:-N31DKpR84euP4aIWMli:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @tanaynigam)

**Pull request merged**
