### PR TITLE
Fix: Add synchronized blocks to prevent ConcurrentModificationException

### PR DESCRIPTION
**Pull request by jennantilla**
# Description
## One Line Summary
Add synchronized blocks to prevent ConcurrentModificationException

### Motivation
Reports of ConcurrentModificationException occurring in various areas of the SDK:

**ModelStore.kt**
- ModelStore.add - #1820 
- ModelStore.persist - #1857 

**Model.kt**
- Model.toJSON - #1856 
- Model.initializeFromModel - #1850 #1819 

**EventProducer.kt**
EventProducer.fire - #1858 

### Scope
The methods reported in the various stack traces were wrapped in synchronized blocks to make them thread-safe.

Additional blocks may need to be added to other areas of the SDK if additional crashes are reported in the future.

# Testing
## Manual testing
The exact conditions needed to trigger these exceptions are unclear--the only way I was able to reproduce a similar crash was from some custom code. Adding synchronized blocks to this code prevented the crash from occurring on Pixel 7 emulator running Android 33. If reproduction steps can be verified, eventual unit tests may be added in the future to help check for these exceptions.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [X] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [X] I have included test coverage for these changes, or explained why they are not needed
   - [X] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [X] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [X] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Android-SDK/1876)

### CODE REVIEW

**Comment by arthurgeron-work** [comment]
Thank you for digging into this issue

**Review by emawby — COMMENTED** [review]
Lets try using the @synchronized class/function annotations to make this read more cleanly.

**Comment by nan-li** [comment]
> Lets try using the @synchronized class/function annotations to make this read more cleanly.

`@synchronized` methods protect methods only and allow one thread to execute a particular method at a time, but different methods can execute at the same time. So it would not be for our purposes. I think we still have to use synchronized blocks.

**Comment by jennantilla** [comment]
@brismithers some additions here based on your analysis in Asana, if you wouldn't mind taking a quick look to ensure I got it all!

**Comment by brismithers** [comment]
*[`OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/modeling/Model.kt` line 125 at r2](https://reviewable.io/reviews/OneSignal/OneSignal-Android-SDK/1876#-NiBBwBM4Z8HM_tawt1c:-NiBBwBM4Z8HM_tawt1d:blzudxu) ([raw file](https://github.com/OneSignal/OneSignal-Android-SDK/blob/e8bf0e89859cb8ddc9b2b85517691f471db3c188/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/modeling/Model.kt#L125)):*
> ```Kotlin
>      */
>     fun initializeFromModel(id: String?, model: Model) {
>         synchronized(initializationLock) {
> ```

I believe the `data.clear()` is needed, if the incoming model doesn't have a particular property set the current model will not have that property removed.  I wonder if it might be safer to build up a local `MutableMap` then at the end replace `data` with the new instance?

**Comment by brismithers** [comment]
*[`OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/modeling/Model.kt` line 127 at r3](https://reviewable.io/reviews/OneSignal/OneSignal-Android-SDK/1876#-NiFCvla3iXuh-4HNgI9:-NiFCvla3iXuh-4HNgIA:bbi0q58) ([raw file](https://github.com/OneSignal/OneSignal-Android-SDK/blob/c742bbf20b194004a9de80497972cd70e5079f45/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/modeling/Model.kt#L127)):*
> ```Kotlin
>         model: Model,
>     ) {
>         val newData = Collections.synchronizedMap(mutableMapOf<String, Any?>())
> ```

nit: this doesn't need to by synchronized since it is only used by this method as a local variable.

**Review by jennantilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Android-SDK/1876)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @brismithers, @emawby, @jkasten2, @nan-li, and @shepherd-l)

___
*[`OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/modeling/Model.kt` line 125 at r2](https://reviewable.io/reviews/OneSignal/OneSignal-Android-SDK/1876#-NiBBwBM4Z8HM_tawt1c:-NiH--YM6mibozgnXeIS:b-896fix) ([raw file](https://github.com/OneSignal/OneSignal-Android-SDK/blob/e8bf0e89859cb8ddc9b2b85517691f471db3c188/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/common/modeling/Model.kt#L125)):*
<details><summary><i>Previously, brismithers (Brian Smith) wrote…</i></summary><blockquote>

I believe the `data.clear()` is needed, if the incoming model doesn't have a particular property set the current model will not have that property removed.  I wonder if it might be safer to build up a local `MutableMap` then at the end replace `data` with the new instance?
</blockquote></details>

Done.

**Review by emawby — APPROVED** [review]

**Pull request merged**
