### PR TITLE
Firebase analytics - auto tracking

### PR DESCRIPTION
**Pull request by Alamgir**
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/338)

### CODE REVIEW

**Comment by jkasten2** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 1497 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/338#-KwvTB2pAnUQwZ15wwEG:-KwvTB2pAnUQwZ15wwEH:bkh7cmk) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/72423db15ba0b2c0b7231a230f18a14291ce17b9/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L1497)):*
> ```Java
>    // Or right when it is received if it is a silent one
>    //   If a NotificationExtenderService is present in the developers app this will not fire for silent notifications.
>    static void handleNotificationReceived(JSONArray data, boolean displayed, boolean fromAlert) {
> ```

`handleNotificationReceived` may not fire for displayed notifications when a NotificationExtenderService is setup in the app. Can you double check this?

---

*[OneSignalSDK/onesignal/src/main/java/com/onesignal/TrackFirebaseAnalytics.java, line 199 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/338#-KwvTa8-2Spzyd3i71g7:-KwvTa8-2Spzyd3i71g8:b-awlrgh) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/72423db15ba0b2c0b7231a230f18a14291ce17b9/OneSignalSDK/onesignal/src/main/java/com/onesignal/TrackFirebaseAnalytics.java#L199)):*
> ```Java
>    private static Method getInstanceMethod(Class clazz) {
>       try {
>          return clazz.getMethod("getInstance", Context.class);
> ```

Can you check if this reflection code still works if prograud is enabled on the app?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/338)*

**Comment by Alamgir** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 1497 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/338#-KwvTB2pAnUQwZ15wwEG:-KwvW10J0T7fo_Jk5e-0:b-5nxudc) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/72423db15ba0b2c0b7231a230f18a14291ce17b9/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L1497)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

`handleNotificationReceived` may not fire for displayed notifications when a NotificationExtenderService is setup in the app. Can you double check this?
</blockquote></details>

if you look at NotificationBundleProcessor.java:397 - the handleNotificationReceived will never be reached

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/338)*

**Comment by Alamgir** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 1497 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/338#-KwvTB2pAnUQwZ15wwEG:-KwvZrnWFi30VJE6ka6T:b37jqa5) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/72423db15ba0b2c0b7231a230f18a14291ce17b9/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L1497)):*
<details><summary><i>Previously, Alamgir (Alamgir Mand) wrote…</i></summary><blockquote>

if you look at NotificationBundleProcessor.java:397 - the handleNotificationReceived will never be reached
</blockquote></details>

verified

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/338)*

**Comment by Alamgir** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[OneSignalSDK/onesignal/src/main/java/com/onesignal/TrackFirebaseAnalytics.java, line 199 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/338#-KwvTa8-2Spzyd3i71g7:-KwvZu2qNsAD4bCAJKlb:b37jqa5) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/72423db15ba0b2c0b7231a230f18a14291ce17b9/OneSignalSDK/onesignal/src/main/java/com/onesignal/TrackFirebaseAnalytics.java#L199)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Can you check if this reflection code still works if prograud is enabled on the app?
</blockquote></details>

verified

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/338)*

**Comment by jkasten2** [comment]
Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/338)*

**Pull request merged**
