### PR TITLE
ANR related to LocationGMS::fireComplete() - optimized synchronization

### PR DESCRIPTION
**Pull request by ron-k**
Related to https://github.com/OneSignal/OneSignal-Android-SDK/issues/283

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/289)

### CODE REVIEW

**Comment by jkasten2** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/289)*

**Comment by jkasten2** [comment]
@ron-k Thanks for the pull! Looks like this should prevent some possible ANRs. Just curious if you were able to reproduce an ANR and if in your testing it fixed the issue?

**Comment by ron-k** [comment]
@jkasten2 Could not reproduce, discovered it from the reports sent by app users

**Comment by BobyIlea** [comment]
@jkasten2 Do you know when will a release with this fix be available? We're not using the source code to build OneSignal library. Thanks.

**Comment by jkasten2** [comment]
@BobyIlea Working on a few more fixes and testing for the 3.6.2 release. Looking on releasing it the beginning of next week.

**Comment by BobyIlea** [comment]
@jkasten2 Great, thanks for letting me know, so we'll wait for 3.6.2.

**Pull request merged**
