### PR TITLE
Active notif restore channel dedup

### PR DESCRIPTION
**Pull request by Alamgir**
- ensuring that notifications already active in the shade are not re-assigned to the "restored" channel on Oreo

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/334)

### CODE REVIEW

**Comment by jkasten2** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationRestorer.java, line 107 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/334#-KwbjgPGAQU8QIQb1Z7I:-KwbjgPGAQU8QIQb1Z7J:bnddhhj) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/c31565b09a5f3979dd7d07bbdd8b6384ae121dd7/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationRestorer.java#L107)):*
> ```Java
> 
>       //retrieve the list of notifications that are currently in the shade
>       if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
> ```

Since `getActiveNotifications()` is available on API Level 23 and higher lets use this as the cut off instead of 26. This way we still get the optimization on omitting the generation of the notification when we don't need to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/334)*

**Comment by Alamgir** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationRestorer.java, line 107 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/334#-KwbjgPGAQU8QIQb1Z7I:-Kwbl9rgeIUtHe0a759f:b615q3i) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/c31565b09a5f3979dd7d07bbdd8b6384ae121dd7/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationRestorer.java#L107)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Since `getActiveNotifications()` is available on API Level 23 and higher lets use this as the cut off instead of 26. This way we still get the optimization on omitting the generation of the notification when we don't need to.
</blockquote></details>

set back to M

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/334)*

**Comment by Alamgir** [comment]
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationRestorer.java, line 107 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/334#-KwbjgPGAQU8QIQb1Z7I:-Kwf_5P1OLro7O1UjGWg:b-896fix) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/c31565b09a5f3979dd7d07bbdd8b6384ae121dd7/OneSignalSDK/onesignal/src/main/java/com/onesignal/NotificationRestorer.java#L107)):*
<details><summary><i>Previously, Alamgir (Alamgir Mand) wrote…</i></summary><blockquote>

set back to M
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/334)*

**Comment by jkasten2** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/334)*

**Pull request merged**
