### PR TITLE
Android Fullbleed IAMs

### PR DESCRIPTION
**Pull request by emawby**
# Description
## One Line Summary
Added support for fullbleed in app messages to the Android SDK. 

## Details
Fullscreen and Carousel In App Messages that do not have margins will now bleed under the status bar to be completely full screen.
The dashboard has added the ability for fullscreen and Carousel IAMs to be created without margins. When doing so it sets `remove_height_margin` and `remove_width_margin` to true in `styles` (this was already being read by the SDK). Currently we don't support only width or height removal so I am consolidating these flags into an isFullscreen boolean that controls the fullbleed behavior. 

In order to handle notched devices we need to tell the Javascript about the device insets so that IAM content doesn't overlap with notches and the status bar. To do this we are modifying the IAMs HTML and calling setSafeAreaInsets with a javascript object of the form
```
{
top: ,
bottom: ,
right: ,
left: ,
}
```

## Version specific notes
Fullbleed is accomplished in two different ways. For API < 30 we use 
```
webView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN |
                   View.SYSTEM_UI_FLAG_IMMERSIVE |
                   View.SYSTEM_UI_FLAG_HIDE_NAVIGATION);
```
For API >=30 we use
`webView.setFitsSystemWindows(false);`

Additionally landscape mode behaves differently in API 29 than all other versions. In API 29 the IAM will bleed under notches whereas in all other versions the IAM will not bleed under. This means we only account for left+right notch insets for API 29.

#### Orientation Change

We also need to call the setSafeAreaInsets() method again if the device is rotated since the side of the notches have changed. To do so we are now responding to the resize javascript event (previously unused).

#### Misc Changes
In order for the IAM to bleed under the status bar we needed to change the popupWindow's display type to `PANEL`. If the IAM is not fullbleed we will still use `attachedDialog`. Additionally we must set `clippingEnabled` to false.

### Motivation
Customer request for full screen IAMs.

### Background Context
When we initially discussed removing margins from IAMs we discussed the future ability to remove just width or height margins so we split them into their own booleans. We eventually decided against that approach and to just focus on fullbleed IAMs.

### Scope
This change involves coordinating new behavior between the SDK and IAM Javascript. It makes no new API calls and provides no new public APIs in the SDK. This change should not affect non fullscreen/carousel IAMs. 

# Testing
## Unit testing
✅  All tests pass after the below modifications
We don't have infrastructure for testing visual properties of IAMs currently or good ways to test a messages HTML content. 

## Manual testing
✅  Tested on various Android emulators and phsyical devices for Android API versions 27-31 with and without notches. Test both carousels and fullscreen IAMs. Tested both landscape and portrait.

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [X] In-App Messaging
   - [ ] REST API requests
   - [ ] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [X] PR does one thing
   - [X] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [X] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [X] Code is as readable as possible.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item

This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481)* status: all files reviewed, 2 unresolved discussions (waiting on @emawby, @Jeasmine, and @nan-li)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/InAppMessageView.java, line 411 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481#-MoBCu1i-nGNu9F_4bPv:-MoBCu1i-nGNu9F_4bPw:bf9fki9) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/65f65d0f139acda4cf9518e6c8c429f6eb082dd2/OneSignalSDK/onesignal/src/main/java/com/onesignal/InAppMessageView.java#L411)):*
> ```Java
>         cardView.setClipToPadding(false);
>         cardView.setPreventCornerOverlap(false);
>         cardView.setCardBackgroundColor(Color.TRANSPARENT);
> ```

This change was already done in PR #1482
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java, line 242 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481#-MoBHxMP3XBFcxJ2uxnD:-MoBHxMP3XBFcxJ2uxnE:b-nzg1zh) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/65f65d0f139acda4cf9518e6c8c429f6eb082dd2/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L242)):*
> ```Java
>         private void handleResize() {
>             if (messageContent.isFullBleed()) {
>                 updateSafeAreaInsets();
> ```

Why is this dependent on a JS resize event? Shouldn't we set this as soon as possible after the JS is ready to receive it?

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481)* status: all files reviewed, 2 unresolved discussions (waiting on @emawby, @Jeasmine, @jkasten2, and @nan-li)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java, line 242 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481#-MoBHxMP3XBFcxJ2uxnD:-MoKDBtw3VDh7TusIAnl:b-ciwn5q) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/65f65d0f139acda4cf9518e6c8c429f6eb082dd2/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L242)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Why is this dependent on a JS resize event? Shouldn't we set this as soon as possible after the JS is ready to receive it?
</blockquote></details>

This for adjusting the insets when the device orientation changes or something else causes the window to resize. The initial insets are already set in the HTML.

Are you thinking there is a better place to update the insets on orientation change?

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @Jeasmine, @jkasten2, and @nan-li)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/InAppMessageView.java, line 411 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481#-MoBCu1i-nGNu9F_4bPv:-MoKEDWoD_32ti4V3bUK:b-896fix) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/65f65d0f139acda4cf9518e6c8c429f6eb082dd2/OneSignalSDK/onesignal/src/main/java/com/onesignal/InAppMessageView.java#L411)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

This change was already done in PR #1482
</blockquote></details>

Done.

**Review by jkasten2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby, @Jeasmine, and @nan-li)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java, line 242 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481#-MoBHxMP3XBFcxJ2uxnD:-MoKL3JS06z5l0bVodJL:b-gpkyzg) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/65f65d0f139acda4cf9518e6c8c429f6eb082dd2/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L242)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

This for adjusting the insets when the device orientation changes or something else causes the window to resize. The initial insets are already set in the HTML.

Are you thinking there is a better place to update the insets on orientation change? 
</blockquote></details>

Yes, thinking insets should be set when the IAM, Activity is resumed, or an orientation change.

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @Jeasmine, @jkasten2, and @nan-li)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java, line 242 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481#-MoBHxMP3XBFcxJ2uxnD:-MoKZAB-2D3ZvksRXtcE:b6tbj4e) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/65f65d0f139acda4cf9518e6c8c429f6eb082dd2/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L242)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Yes, thinking insets should be set when the IAM, Activity is resumed, or an orientation change.
</blockquote></details>

Gotcha I removed it. I was already calling it `calculateHeightAndShowWebViewAfterNewActivity` which is called on orientation change and makes sense to call update insets here

**Review by jkasten2 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jeasmine and @nan-li)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java, line 242 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1481#-MoBHxMP3XBFcxJ2uxnD:-MoKcVbHEdnsLaAFOlzG:b4c9lyr) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/65f65d0f139acda4cf9518e6c8c429f6eb082dd2/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L242)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

Gotcha I removed it. I was already calling it `calculateHeightAndShowWebViewAfterNewActivity` which is called on orientation change and makes sense to call update insets here
</blockquote></details>

:thumbsup:

**Pull request merged**
