### PR TITLE
Feature no margin IAMs

### PR DESCRIPTION
**Pull request by emawby**
As part of enabling our IAMs to be displayed with no margins I made more changes that should allow us to more easily make IAM enhancements in the future.

New class `OSInAppMessageContent` can be used to parse data from the `loadHTMLContent` request and is used to pass data between the `OSInAppMessageController`, `WebViewManager`, and `OSInAppMessageView`.

This object will store the HTML to display, the margin data sent in the new styles JSON object, and the display duration.

Additional Changes:
We are now properly using relativeLayout parameters instead of linearLayout parameters for our InAppMessageView's relativeLayout. 

OSInAppMessagePage was mistakenly public. I am changing the access level to internal (this can be cherry picked to its own PR if desired)

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422)

### CODE REVIEW

**Review by Jeasmine — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422)* status: all files reviewed, 4 unresolved discussions (waiting on @emawby and @nan-li)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OSInAppMessageContent.kt, line 13 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422#-MiMsa6l2M8KEJ7IFwxE:-MiMsa6l2M8KEJ7IFwxF:b-dwmo6s) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/b5469e9f7e03d49b5d15589cffb435eb14895744/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSInAppMessageContent.kt#L13)):*
> ```Kotlin
> const val RIGHT_MARGIN = "right_margin"
> 
> internal open class OSInAppMessageContent constructor(jsonObject: JSONObject) {
> ```

Do you need this class to be open?
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java, line 204 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422#-MiMw3qUDTXM-B46vHUk:-MiMw3qUDTXM-B46vHUl:b-yltytx) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/b5469e9f7e03d49b5d15589cffb435eb14895744/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L204)):*
> ```Java
>             int pageHeight = displayType == Position.FULL_SCREEN ? -1 : getPageHeightData(jsonObject);
>             boolean dragToDismissDisabled = getDragToDismissDisabled(jsonObject);
>             messageContent.setDisplayLocation(displayType);
> ```

Is it safe to mutate the message content inside the webviewManager?

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @emawby, @jkasten2, and @nan-li)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/InAppMessageView.java, line 322 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422#-Mi8TOBw3Ska7qwLRxKf:-MiMx97N-h3Vumw2wKB-:b-896fix) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/b5469e9f7e03d49b5d15589cffb435eb14895744/OneSignalSDK/onesignal/src/main/java/com/onesignal/InAppMessageView.java#L322)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

Remove blank comment block
</blockquote></details>

Done.

**Review by emawby — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @Jeasmine, @jkasten2, and @nan-li)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OSInAppMessageContent.kt, line 13 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422#-MiMsa6l2M8KEJ7IFwxE:-MiMxHes-iWb0YvOSyRu:b-cdkpg1) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/b5469e9f7e03d49b5d15589cffb435eb14895744/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSInAppMessageContent.kt#L13)):*
<details><summary><i>Previously, Jeasmine (JNahui) wrote…</i></summary><blockquote>

Do you need this class to be open?
</blockquote></details>

It doesn't need to be open since nothing is inheriting from it right now, but we aren't marking our Java classes as Final right now as many of them are overridden by a Mock for unit testing. I think this OSInAppMessageContent should be open for extension by unit tests, but maybe we can leave it final until it is needed. This is something I think we could decide as a standard style for Kotlin classes that aren't being inherited from. 
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java, line 204 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422#-MiMw3qUDTXM-B46vHUk:-MiMydkz-G395i_xT1nC:blwuyeq) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/b5469e9f7e03d49b5d15589cffb435eb14895744/OneSignalSDK/onesignal/src/main/java/com/onesignal/WebViewManager.java#L204)):*
<details><summary><i>Previously, Jeasmine (JNahui) wrote…</i></summary><blockquote>

Is it safe to mutate the message content inside the webviewManager?
</blockquote></details>

Yep the values for page height and display location come from the rendering complete Javascript event, not from loadMessageContent HTML request. We were doing this before by passing the values into the constructor for the InAppMessageView so this is not a change just putting those parameters into the new object.

**Review by emawby — COMMENTED** [review]
confirmed with Guy and made the change to height width booleans

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422#-:-MiO3d_97suaUixL71wb:b-2peh1b)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @Jeasmine, @jkasten2, and @nan-li)

**Review by jkasten2 — APPROVED** [review]
PR looks good to me now, just had one nit on simplifying logic, but not a blocker.

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422#-:-Mi_0yCs6EUa_QYg7qvX:b-crak8m)* status: all files reviewed, 4 unresolved discussions (waiting on @emawby, @Jeasmine, and @nan-li)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OSInAppMessageContent.kt, line 13 at r3](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422#-MiMsa6l2M8KEJ7IFwxE:-Mi_0aGACCTJsNjUHJ4U:bch5hs0) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/b5469e9f7e03d49b5d15589cffb435eb14895744/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSInAppMessageContent.kt#L13)):*
<details><summary><i>Previously, emawby (Elliot Mawby) wrote…</i></summary><blockquote>

It doesn't need to be open since nothing is inheriting from it right now, but we aren't marking our Java classes as Final right now as many of them are overridden by a Mock for unit testing. I think this OSInAppMessageContent should be open for extension by unit tests, but maybe we can leave it final until it is needed. This is something I think we could decide as a standard style for Kotlin classes that aren't being inherited from. 
</blockquote></details>

I am ok with either for this PR, we can follow up later outside of this PR.
___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OSInAppMessageContent.kt, line 24 at r5](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1422#-Mi_-glv3OC6khgt9a7e:-Mi_-glv3OC6khgt9a7f:bxd27pw) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/e5245314b58c19344ff0c0a1305578255bbd7cad/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSInAppMessageContent.kt#L24)):*
> ```Kotlin
>         displayDuration = jsonObject.optDouble(DISPLAY_DURATION)
>         var styles: JSONObject? = jsonObject.optJSONObject(STYLES)
>         useHeightMargin = !(styles?.optBoolean(REMOVE_HEIGHT_MARGIN, false) ?: false)
> ```

The extra not wrapping is confusing. I believe we can simplify this to the following:
`useHeightMargin = styles?.optBoolean(REMOVE_HEIGHT_MARGIN, true) ?: true`

**Pull request merged**
