### PR TITLE
Support: reference value for ManifestMeta

### PR DESCRIPTION
**Pull request by lekaha**
Hi,

Raising this PR for supporting reference value of Meta data in AndroidManifest. 

The motivation of this for me was I found there is a `ClassCastException`  when I tried to put a reference color to `com.onesignal.NotificationAccentColor.DEFAULT` and wanted to have different accent colors for Dark mode and Light mode. 

Thinking it might be better to support it with the following usage,

1. color reference 

```
<meta-data android:name="com.onesignal.NotificationAccentColor.DEFAULT"
        android:resource="@color/onesignal_notification_accent" />
```

1. color string value

```
<meta-data android:name="com.onesignal.NotificationAccentColor.DEFAULT"
        android:value="FF00FF00" />
```

In the case of giving both `resource` and `value`, for example,

```
<meta-data android:name="com.onesignal.NotificationAccentColor.DEFAULT"
        android:resource="@color/onesignal_notification_accent"
        android:value="FF00FF00" />
```

The `resource` will be taken. 

For other meta data will be continuing compatible.

Thanks.

## 
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1251)

### CODE REVIEW

**Comment by lekaha** [comment]
The CI is even failing on main branch.

**Comment by lekaha** [comment]
Hi @Jeasmine , 

Haven seen you are the last person merged PR so reaching you.
Are you still maintaining this repo? My PR has been opened for a while but no any response wondering if it means you are not opening for PR? or?

**Comment by Jeasmine** [comment]
> Hi @Jeasmine ,
> 
> Haven seen you are the last person merged PR so reaching you.
> Are you still maintaining this repo? My PR has been opened for a while but no any response wondering if it means you are not opening for PR? or?

Hi @lekaha, thanks for your contribution. We still didn't have time to test it. That is why there is no comment

**Comment by jkasten2** [comment]
To support dark mode we now check for the resource named `onesignal_notification_accent_color`, this way you don't need to add any `AndroidManifest.xml` changes. The [OneSignal Small Icon Accent Color](https://documentation.onesignal.com/docs/customize-notification-icons#small-icon-accent-color) documentation will be updated shortly with examples and you can also see PR #1370 for more details. This was feature was released in [4.4.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.4.1).

**Pull request closed without merging**
