### PR TITLE
Onesignal javadocs

### PR DESCRIPTION
**Pull request by Alamgir**
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/313)

### CODE REVIEW

**Comment by Alamgir** [comment]
Travis CI build now passes

**Comment by jkasten2** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[OneSignalSDK/unittest/src/test/java/com/test/onesignal/MainOneSignalClassRunner.java, line 194 at r1](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/313#-Kv6a9zM2ayXMPRLaXHO:-Kv6a9zM2ayXMPRLaXHP:bv6c0e2) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/fa54052b16b13e5926ae45c99bb3ce9d302f641b/OneSignalSDK/unittest/src/test/java/com/test/onesignal/MainOneSignalClassRunner.java#L194)):*
> ```Java
>    @After
>    public void afterEachTest() throws Exception {
>       Thread.sleep(100*100);
> ```

This may have helped but one of the test is still flaky
```
com.test.onesignal.MainOneSignalClassRunner > testDeleteTags FAILED
    junit.framework.AssertionFailedError at MainOneSignalClassRunner.java:1134
```
https://travis-ci.org/OneSignal/OneSignal-Android-SDK/builds/280672644?utm_source=github_status&utm_medium=notification

`threadAndTaskWait` might be the compabitliy here. It used to have a 2 second delay on travis before it was refactored that we may want to introduce again.
https://github.com/OneSignal/OneSignal-Android-SDK/commit/5fd4cc230c4793a7e1db8e4fdb1d46c0d171bb42#diff-30682d337c98dc4f554a8b9215c4ca53L162

It seems the tests are 2 times on each build, it is running `:unittest:testReleaseUnitTest` and `:unittest:testDebugUnitTest`. Limiting to just the release target show speed up travis build times.

Lastly the javadocs and travis builds are 2 very different commits. Let split up unrelated tasks like this into 2 branches / pulls in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/313)*

**Comment by Alamgir** [comment]
moved the travis/unit test changes to another branch

**Comment by jkasten2** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/onesignal/onesignal-android-sdk/313)*

**Pull request merged**
