### PR TITLE
Add public get tags method

### PR DESCRIPTION
**Pull request by jinliu9508**
# Description
## One Line Summary
Add a public getTags method

### Motivation
Provide a public getTags upon request

### Scope
We are only returning the local tags

# Testing
## Unit testing
Add one unit test to ensure the data is the same

## Manual testing
I ran it in an emulator, added a tag, and the call of getTags returns that tag

# Affected code checklist
   - [ ] Notifications
      - [ ] Display
      - [ ] Open
      - [ ] Push Processing
      - [ ] Confirm Deliveries
   - [ ] Outcomes
   - [ ] Sessions
   - [ ] In-App Messaging
   - [ ] REST API requests
   - [x] Public API changes

# Checklist
## Overview
   - [x] I have filled out all **REQUIRED** sections above
   - [x] PR does one thing
     - If it is hard to explain how any codes changes are related to each other then it most likely needs to be more than one PR
   - [x] Any Public API changes are explained in the PR details and conform to existing APIs

## Testing
   - [x] I have included test coverage for these changes, or explained why they are not needed
   - [x] All automated tests pass, or I explained why that is not possible
   - [x] I have personally tested this on my device, or explained why that is not possible

## Final pass
   - [x] Code is as readable as possible.
      - Simplify with less code, followed by splitting up code into well named functions and variables, followed by adding comments to the code.
   - [x] I have reviewed this PR myself, ensuring it meets each checklist item
      - WIP (Work In Progress) is ok, but explain what is still in progress and what you would like feedback on. Start the PR title with "WIP" to indicate this.

- - -
This change is [Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Android-SDK/1893)

### CODE REVIEW

**Review by emawby — CHANGES_REQUESTED** [review]
This looks great! I believe the code is correct, but for future proofing lets add a test where the user changes (causing the tags to change) and verify that when we switch users we get the updated tags.

**Comment by jinliu9508** [comment]
@emawby Good point! A new test case for tags modification is added in this PR. Please have a look!

**Review by emawby — CHANGES_REQUESTED** [review]
It looks like the linter is failing. You may need to rebase since changes were merged that fix linting

**Review by emawby — APPROVED** [review]

**Comment by shepherd-l** [comment]
I noticed that the linter check is still failing, could you fix the linter indentation errors in UserManagerTests?

Also just a nit but, I think the Migration Guide could be updated to include `getTags` in the [API Reference](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md#api-reference) section

**Comment by jinliu9508** [comment]
> I noticed that the linter check is still failing, could you fix the linter indentation errors in UserManagerTests?
> 
> Also just a nit but, I think the Migration Guide could be updated to include `getTags` in the [API Reference](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md#api-reference) section

@shepherd-l Thanks, Shepherd! I have fixed the linter error and added 'getTags' in the Migration Guide. Please have a look.

**Review by shepherd-l — APPROVED** [review]
Looks good to me!

> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/OneSignal/OneSignal-Android-SDK/1893#-:-NjODHV87YWki63BrFKy:b9j9n3q)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @jennantilla, @jkasten2, and @nan-li)

**Pull request merged**
