### PR TITLE
Feature App-defined Language implementation backported to 3.X.X version

### PR DESCRIPTION
**Pull request by tanaynigam**
# Description
Add feature app-defined language implementation. A user can define their own language setting to be used by OneSignal-SDK version 3.X.X. Cherry picked from OneSignal-SDK version 4.4.0 PR #1334 

## Details
* Add `LanguageContext`, `LanguageProviderAppDefined` and `LanguageProviderDevice` class and `LanguageProvider` interface
* Add `OneSignal.setLanguage` implementation
* Add `runSetLanguage` runnable to `OneSignal.setLanguage` for network call implementation. Add runnable to addTaskToQueue

## Test
* Add MainOneSignalClassRunner testSetLanguageOnPlayerCreate, testSetLanguagePUTRequest, testSetLanguageOnSession unit tests
* Test device using button click to call OneSignal.setLanguage to set it to language different from language defined by the device. OneSignal app dashboard reflects the language set using OneSignal.setLanguage

---
This change is [Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1350)

### CODE REVIEW

**Review by jkasten2 — CHANGES_REQUESTED** [review]
Remove .ds_store file

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1350#-:-Map2S5h1sNEiQQuRhps:b-7ro18s)* status: all files reviewed, 1 unresolved discussion (waiting on @emawby, @Jeasmine, and @tanaynigam)

___
*[OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java, line 745 at r1](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1350#-Map2rSz638MWK6CFN5u:-Map2rSz638MWK6CFN5v:bwbbp4i) ([raw file](https://github.com/onesignal/onesignal-android-sdk/blob/39fc97c1da7a904b535aadfe725ee18bcef0de44/OneSignalSDK/onesignal/src/main/java/com/onesignal/OneSignal.java#L745)):*
> ```Java
> 
>       // Initialize languageContext
>       languageContext = new LanguageContext(preferences);
> ```

We are already creating an instance of `setAppContext` so we should remove this one.

**Review by emawby — APPROVED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1350)* status: all files reviewed, 1 unresolved discussion (waiting on @Jeasmine and @tanaynigam)

**Review by Jeasmine — APPROVED** [review]
LGTM after josh's comments are done

**Review by jkasten2 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1350)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tanaynigam)

**Review by jkasten2 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-android-sdk/1350)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tanaynigam)

**Pull request merged**
